<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AssemblyName>RhinoMM.Core</AssemblyName>
    <RootNamespace>RhinoMM.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\data\fastener-presets.v1.json" Link="Data\fastener-presets.v1.json" />
    <EmbeddedResource Include="..\..\data\locking-nut-presets.v1.json" Link="Data\locking-nut-presets.v1.json" />
  </ItemGroup>
</Project>
